//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Psychic.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Psychic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Team ReplingCube
        ///&lt;기획&gt;김승민
        ///&lt;그래픽&gt;윤성진
        ///&lt;프로그래밍&gt;
        ///진재연
        ///김여원과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Credit_Description {
            get {
                return ResourceManager.GetString("Credit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 우리가 리사를 감금한지 20일이 경과했다. 현재 그녀의 초능력은 상상을 초월할 정도로 매우 강력하였다. 지금 당장은 활용하기엔 힘들지만 그녀에 대해서 더 정밀한 조사가 가능하다면 군사용으로도 활용이 가능할 것 같다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Document_01_Desc {
            get {
                return ResourceManager.GetString("Document_01_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   리사 연구 보고서-01과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Document_01_Title {
            get {
                return ResourceManager.GetString("Document_01_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 그녀를 연구하고 있는 동안에 많은 사상자가 발생하였다. 어제도 3명이나 죽고 이 글을 쓰는 동안에도 1명이 죽었다. 이렇게 무리하면서 까지 그들이 원하는 것은 도대체 무엇일까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Document_02_Desc {
            get {
                return ResourceManager.GetString("Document_02_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   의문의 보고서과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Document_02_Title {
            get {
                return ResourceManager.GetString("Document_02_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그녀의 어렸을 때는 정말 평범한 어린아이와 같았다. 초능력을 사용하는 것을 제외하고 그녀는 무의식적으로 초능력을 사용했었고 그것을 연구하기 위해서 연구실에 감금시키고 온갖 실험을 강행하였다. 그녀가 혼수상태에 빠져서야 그들은 실험을 중단하기 이르렀다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Document_03_Desc {
            get {
                return ResourceManager.GetString("Document_03_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   리사 연구 보고서-02과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Document_03_Title {
            get {
                return ResourceManager.GetString("Document_03_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   혼수상태에서 깨어난 그녀는 이미 평범한 인간이 되어있었다. 연기일줄 알았지만 실제로 그녀는 초능력을 완전히 상실해버린 것이다. 그때서야 정부에서는 그녀를 죽이기로 했으나 죽이기 전날 밤에 누군가가 그녀를 빼돌리게 되었고 그녀에 대해서는 그 이후로는 소식이 없다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Document_04_Desc {
            get {
                return ResourceManager.GetString("Document_04_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   리사 연구 보고서-03과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Document_04_Title {
            get {
                return ResourceManager.GetString("Document_04_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   10월 23일에 리사를 다시 발견했을 때는 아무런 징조가 없었으나 12월 초부터 그녀는 어느새 초능력을 사용하고 있었다. 그러나 정작 본인은 모르고 있는듯하나 정부에서 눈치채기 전에 우리가 먼저 그녀의 신병을 확보해야 한다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Document_05_Desc {
            get {
                return ResourceManager.GetString("Document_05_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   회의록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Document_05_Title {
            get {
                return ResourceManager.GetString("Document_05_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   어젯밤 GH사의 비밀연구소에서 초능력자들을 발견했다는 정보를 입수하였다. 아마도 그들은 초능력자를 이용해서 군용무기를 만들려는 속셈인 듯 하다. 초능력자의 신병확보 후에 연구소를 완전파괴시켜야 한다. 만약 초능력자의 신병확보가 불가능하면 사살하여도 상관없다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Document_06_Desc {
            get {
                return ResourceManager.GetString("Document_06_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작전설명쪽지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Document_06_Title {
            get {
                return ResourceManager.GetString("Document_06_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그를 맨 처음 데려왔을 때에는 누구도 그가 사람을 죽일 줄은 몰랐을 것이다. 그러나 그는 이제 실험을 견뎌내지 못하고 폭주하여 어제도 4명이나 죽였고 일주일 전에는 23명의 연구원들이 죽거나 다쳤다. 그렇지만 그도 리사보다는 나은 편이다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Document_07_Desc {
            get {
                return ResourceManager.GetString("Document_07_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스티브 연구 보고서과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Document_07_Title {
            get {
                return ResourceManager.GetString("Document_07_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   만약 작전 시작 후 8시간이 지나도 목표를 확보하지 못할 시에 건물 자체를 폭파시킨다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Document_08_Desc {
            get {
                return ResourceManager.GetString("Document_08_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작전지침서과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Document_08_Title {
            get {
                return ResourceManager.GetString("Document_08_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   누나가 이 편지를 봤을 때엔 난 이미 죽어있을거야. 알고 보니 누나랑 나는 초능력자를 만들기 위해 서 일부러 인공 수정한 쌍둥이 남매였어. 그리고는 우리 남매를 무자비하게 실험을 했지. 이제 그 사실을 세상에 알릴 거야. 이제 그들은… (훼손되어 읽을 수가 없다.)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Document_09_Desc {
            get {
                return ResourceManager.GetString("Document_09_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   리사에게과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Document_09_Title {
            get {
                return ResourceManager.GetString("Document_09_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   12월에 초능력자에게 접근한 남자는 코드명 Mr. E로 칭한다. 입수한 정보에 따르면 그는 세계정복이라는 터무니 없는 망상을 가지고 있었다. 하지만 그는 실제로 웬만한 후진국보다 큰 세력을 가지고 있었고 이제는 초능력자 마저도 그의 손아귀에 넣으려고 하고 있다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Document_10_Desc {
            get {
                return ResourceManager.GetString("Document_10_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   코드명 Mr. E에 대해서과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Document_10_Title {
            get {
                return ResourceManager.GetString("Document_10_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   얻지 못한 문서과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Document_DidntTakeDoc {
            get {
                return ResourceManager.GetString("Document_DidntTakeDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   문이 잠겨있네.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_DoorLocked {
            get {
                return ResourceManager.GetString("Message_DoorLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   뒤를 조심하라고?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Ending_Scene_1 {
            get {
                return ResourceManager.GetString("Message_Ending_Scene_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   꺄악!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Ending_Scene_2 {
            get {
                return ResourceManager.GetString("Message_Ending_Scene_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Ending_Scene_3 {
            get {
                return ResourceManager.GetString("Message_Ending_Scene_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   여기는 도대체...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_1_1 {
            get {
                return ResourceManager.GetString("Message_Event_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   드디어 깨어나셨군요. 당신을 기다렸습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_1_2 {
            get {
                return ResourceManager.GetString("Message_Event_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   당신은 누구시죠?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_1_3 {
            get {
                return ResourceManager.GetString("Message_Event_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   차차 알아가게 될 겁니다. 그러면 저는 이만...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_1_4 {
            get {
                return ResourceManager.GetString("Message_Event_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아! 예전과는 다른 뭔가가 느껴지지 않습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_1_5 {
            get {
                return ResourceManager.GetString("Message_Event_1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저 자식... 아무래도 밖으로 나가야 될 거 같은데...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_1_6 {
            get {
                return ResourceManager.GetString("Message_Event_1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   15분 쯤 늦었군요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_10_1 {
            get {
                return ResourceManager.GetString("Message_Event_10_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검은 양복! 여기는 대체 뭐 하는 곳이지? 단순한 연구실로는 보이지 않는데?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_10_2 {
            get {
                return ResourceManager.GetString("Message_Event_10_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   글쎄요... 제가 만들었지만 저도 이곳이 도대체 뭐하는 곳인지 모르겠습니다. 역시 방해꾼의 역할이 큰 것 같군요. 물론 덕분에 좋은 구경도 합니다만. 이런, 저는 아무래도 당신을 앞질러 간 사람을 만나야 되겠군요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_10_3 {
            get {
                return ResourceManager.GetString("Message_Event_10_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그럼 이만...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_10_4 {
            get {
                return ResourceManager.GetString("Message_Event_10_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도대체 아는게 뭔지... 15분 쯤 늦었다고?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_10_5 {
            get {
                return ResourceManager.GetString("Message_Event_10_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   혹시 스티브가 여길 15분 전에 지나쳤다는 얘긴가?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_10_6 {
            get {
                return ResourceManager.GetString("Message_Event_10_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   여기있었군, 스티브.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_17_1 {
            get {
                return ResourceManager.GetString("Message_Event_17_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그 일이라는게 사람들을 죽이는 거야? 아무리 우리를 연구에 이용했다지만 그렇다고 무고한 사람들까지 죽일 필요까진 없잖아?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_17_10 {
            get {
                return ResourceManager.GetString("Message_Event_17_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   무고하다니... 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_17_11 {
            get {
                return ResourceManager.GetString("Message_Event_17_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그런가... 그놈인가?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_17_12 {
            get {
                return ResourceManager.GetString("Message_Event_17_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   충고하나 하지.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_17_13 {
            get {
                return ResourceManager.GetString("Message_Event_17_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mr. E, 그녀석은 믿지마.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_17_14 {
            get {
                return ResourceManager.GetString("Message_Event_17_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mr. E? 검은 양복을 말하는 건가?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_17_15 {
            get {
                return ResourceManager.GetString("Message_Event_17_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아까부터 날 쫓아온 이유가 뭐야?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_17_2 {
            get {
                return ResourceManager.GetString("Message_Event_17_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   너에 관한 것과 나에 관한 것.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_17_3 {
            get {
                return ResourceManager.GetString("Message_Event_17_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   글쎄, 나도 자세히는 몰라. 아직 조사중이고.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_17_4 {
            get {
                return ResourceManager.GetString("Message_Event_17_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   무슨...?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_17_5 {
            get {
                return ResourceManager.GetString("Message_Event_17_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이렇게 된 김에 나와 같이 이곳을 나가자. 나는 이런 곳에서 썩을 순 없다고.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_17_6 {
            get {
                return ResourceManager.GetString("Message_Event_17_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   거기까지.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_17_7 {
            get {
                return ResourceManager.GetString("Message_Event_17_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   협상 결렬이군...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_17_8 {
            get {
                return ResourceManager.GetString("Message_Event_17_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   나는 여기서 나가야 해. 나가서 꼭 해야할 일이 있다고.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_17_9 {
            get {
                return ResourceManager.GetString("Message_Event_17_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도대체 내 몸이 어떻게 되어버린 거야?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_2_1 {
            get {
                return ResourceManager.GetString("Message_Event_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   드디어 오셨군요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_20_1 {
            get {
                return ResourceManager.GetString("Message_Event_20_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mr. E...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_20_2 {
            get {
                return ResourceManager.GetString("Message_Event_20_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   예, 제가 Mr. E 입니다. 스티브에게서 저에 대해서 들었죠?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_20_3 {
            get {
                return ResourceManager.GetString("Message_Event_20_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전혀...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_20_4 {
            get {
                return ResourceManager.GetString("Message_Event_20_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스티브가 아직도 살아있다니 정말 아쉽군요. 빨리 처치하시기 바랍니다. 그는 제정신이 아니니까요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_20_5 {
            get {
                return ResourceManager.GetString("Message_Event_20_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   뻔한 속임수에 내가 넘어갈거라 생각하면 오산이지.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_20_6 {
            get {
                return ResourceManager.GetString("Message_Event_20_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   혹시 스티브?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_24_1 {
            get {
                return ResourceManager.GetString("Message_Event_24_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도대체 여기서는 무슨 일이 벌어지고 있는 거지?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_3_1 {
            get {
                return ResourceManager.GetString("Message_Event_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아무래도 여긴 평범한 연구소가 아닌 것 같아.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_3_2 {
            get {
                return ResourceManager.GetString("Message_Event_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   당신은?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_4_1 {
            get {
                return ResourceManager.GetString("Message_Event_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이제 슬슬 힘에 눈을 뜨셨겠죠? 하지만 저희는 아직 더 알고 싶은것이 많습니다. 좀 더 고생을 해주셔야 할 것 같군요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_4_2 {
            get {
                return ResourceManager.GetString("Message_Event_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아! 제 앞에서는 당신의 힘이 통하진 않을겁니다. 그 점 참고해두시길...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_4_3 {
            get {
                return ResourceManager.GetString("Message_Event_4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_4_4 {
            get {
                return ResourceManager.GetString("Message_Event_4_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   어? 아직도 여기 민간인이...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_5_1 {
            get {
                return ResourceManager.GetString("Message_Event_5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아뇨 괜찮습니다. 가까운 곳에 의무실이 있던거 같은데...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_5_10 {
            get {
                return ResourceManager.GetString("Message_Event_5_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그럼 전 이만...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_5_11 {
            get {
                return ResourceManager.GetString("Message_Event_5_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도대체... 이런 곳 어디에 의무실이 있다는 건지...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_5_12 {
            get {
                return ResourceManager.GetString("Message_Event_5_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   으윽...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_5_2 {
            get {
                return ResourceManager.GetString("Message_Event_5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저기... 당신은 누구죠?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_5_3 {
            get {
                return ResourceManager.GetString("Message_Event_5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저는 스티브라고 합니다. 혹시 당신도 여기 감금당했나요?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_5_4 {
            get {
                return ResourceManager.GetString("Message_Event_5_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아마도 그런거 같은데요...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_5_5 {
            get {
                return ResourceManager.GetString("Message_Event_5_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   역시... 그때 돈을 갚았어야 했는데!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_5_6 {
            get {
                return ResourceManager.GetString("Message_Event_5_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저기요 혹시 여기서 무슨일이 있었는지 알고 계세요?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_5_7 {
            get {
                return ResourceManager.GetString("Message_Event_5_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아뇨 저는 그때 기절해버려서 아무것도 모르... 콜록 콜록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_5_8 {
            get {
                return ResourceManager.GetString("Message_Event_5_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   피가 나네요! 어서 응급처치를...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_5_9 {
            get {
                return ResourceManager.GetString("Message_Event_5_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   젠장 역시 그 녀석을 잡아 뒀어야 했어! 다음에 만나면 반드시 잡아주마!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_6_1 {
            get {
                return ResourceManager.GetString("Message_Event_6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다시 만나는군.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_7_1 {
            get {
                return ResourceManager.GetString("Message_Event_7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기다려! 뭐야 저녀석 자기 할 말만 하고 가버리고...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_7_10 {
            get {
                return ResourceManager.GetString("Message_Event_7_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   혹시 그 녀석이 스티브?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_7_11 {
            get {
                return ResourceManager.GetString("Message_Event_7_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오랜만입니다. 그동안 건강히 지냈는지? 뭐 아직 장난이 덜하군요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_7_2 {
            get {
                return ResourceManager.GetString("Message_Event_7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (역시 멋대로 지껄이는군)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_7_3 {
            get {
                return ResourceManager.GetString("Message_Event_7_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아직 당신의 동료를 만나보지 못했습니까? 이 건물에 한 명 더 있는 걸로 알고 있습니다만.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_7_4 {
            get {
                return ResourceManager.GetString("Message_Event_7_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ?!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_7_5 {
            get {
                return ResourceManager.GetString("Message_Event_7_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   여기에 있는 사람들을 죽인 건 그라고 알고 있는 데요?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_7_6 {
            get {
                return ResourceManager.GetString("Message_Event_7_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도대체 무슨 말을 하려는 거죠?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_7_7 {
            get {
                return ResourceManager.GetString("Message_Event_7_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아마 그는 이곳을 나가면 모든 사람들을 죽이려 할테죠.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_7_8 {
            get {
                return ResourceManager.GetString("Message_Event_7_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아마도요. 그것을 막을 수 있는 사람은 당신 밖에 없는 듯 싶습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_7_9 {
            get {
                return ResourceManager.GetString("Message_Event_7_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   여기 있는 것들 모두 스티브의 짓이겠지? 일단 그 검은 양복 녀석 말은 맞는 것 같긴 한데...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_8_1 {
            get {
                return ResourceManager.GetString("Message_Event_8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아무래도 스티브를 막아야겠어.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_8_2 {
            get {
                return ResourceManager.GetString("Message_Event_8_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   드디어 만났군.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_9_1 {
            get {
                return ResourceManager.GetString("Message_Event_9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_9_2 {
            get {
                return ResourceManager.GetString("Message_Event_9_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그건 그렇고 너의 목적이 뭐야?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_9_3 {
            get {
                return ResourceManager.GetString("Message_Event_9_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아직 생각한 것은 없어. 그저...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_9_4 {
            get {
                return ResourceManager.GetString("Message_Event_9_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그저?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_9_5 {
            get {
                return ResourceManager.GetString("Message_Event_9_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이곳에서 벗어나고 싶을 뿐이야.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_9_6 {
            get {
                return ResourceManager.GetString("Message_Event_9_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   또 사라져버렸군. 역시 나와 같은 능력을 사용하는 건가?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Event_9_7 {
            get {
                return ResourceManager.GetString("Message_Event_9_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장하지 못하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_FailedSave {
            get {
                return ResourceManager.GetString("Message_FailedSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}번 문서를 얻었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_GotDocument {
            get {
                return ResourceManager.GetString("Message_GotDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경보기구나. 투명화를 사용해야겠다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Help_Alert {
            get {
                return ResourceManager.GetString("Message_Help_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   압축기? 조심해서 지나가자.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Help_Compressor {
            get {
                return ResourceManager.GetString("Message_Help_Compressor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   문이구나. 위쪽 화살표 키로 들어가자.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Help_Door {
            get {
                return ResourceManager.GetString("Message_Help_Door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   낭떠러지인가... 순간이동을 써야겠다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Help_Teleport_Cliff {
            get {
                return ResourceManager.GetString("Message_Help_Teleport_Cliff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   거울인가... 순간이동을 써야겠다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Help_Teleport_Mirror {
            get {
                return ResourceManager.GetString("Message_Help_Teleport_Mirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   앞에 있는건 덫인가... 저 군인을 이용하자.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Help_Trap {
            get {
                return ResourceManager.GetString("Message_Help_Trap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2009년 1월 1일 올해도 새해가 밝았다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Opening_Scene_1_1 {
            get {
                return ResourceManager.GetString("Message_Opening_Scene_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   평소와 다를 것 없는 일상.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Opening_Scene_1_2 {
            get {
                return ResourceManager.GetString("Message_Opening_Scene_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   하지만...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Opening_Scene_2_1 {
            get {
                return ResourceManager.GetString("Message_Opening_Scene_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그 일상은 조금씩과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Opening_Scene_2_2 {
            get {
                return ResourceManager.GetString("Message_Opening_Scene_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   일그러져 나에게로 다가왔다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Opening_Scene_3_1 {
            get {
                return ResourceManager.GetString("Message_Opening_Scene_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Saved {
            get {
                return ResourceManager.GetString("Message_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;환경설정&gt;
        ///소리 : ON  OFF과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Option_Text {
            get {
                return ResourceManager.GetString("Option_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [리사]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Talker_Lisa {
            get {
                return ResourceManager.GetString("Talker_Lisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Mr. E]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Talker_MrE {
            get {
                return ResourceManager.GetString("Talker_MrE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [???]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Talker_MrE_Unknown {
            get {
                return ResourceManager.GetString("Talker_MrE_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [스티브]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Talker_Steve {
            get {
                return ResourceManager.GetString("Talker_Steve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [???]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Talker_Steve_Unknown {
            get {
                return ResourceManager.GetString("Talker_Steve_Unknown", resourceCulture);
            }
        }
    }
}
